Demonstrate issue with baseTypeWithArgs
> run try/unittest_iterator.scala
[info] Running dotty.tools.dotc.Main try/unittest_iterator.scala
[info] tp1: Foo{A = Outer$Bar$$B; Outer$Bar$$B = Int}
[info] parent1: Foo[Outer$Bar$$B]
[info] parent1.classSymbol: class Foo
[info] tp1.baseTypeWithArgs(parent1.classSymbol): Foo[Outer$Bar$$B]
[error] try/unittest_iterator.scala:16: error: type mismatch:
[error]  found   : Foo{A = Outer$Bar$$B; Outer$Bar$$B = Int}
[error]  required: Foo[Int]
[error]     val foo: Foo[Int] = {
[error]                         ^
[error] one error found